// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/plimble/repass (interfaces: Store,Interface)

package repass

import (
	mailba "github.com/plimble/mailba"
	time "time"
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *_MockStoreRecorder
}

// Recorder for MockStore (not exported)
type _MockStoreRecorder struct {
	mock *MockStore
}

func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &_MockStoreRecorder{mock}
	return mock
}

func (_m *MockStore) EXPECT() *_MockStoreRecorder {
	return _m.recorder
}

func (_m *MockStore) Get(_param0 string) (*Token, error) {
	ret := _m.ctrl.Call(_m, "Get", _param0)
	ret0, _ := ret[0].(*Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) Get(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0)
}

func (_m *MockStore) Insert(_param0 interface{}) error {
	ret := _m.ctrl.Call(_m, "Insert", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) Insert(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Insert", arg0)
}

func (_m *MockStore) Update(_param0 string, _param1 map[string]interface{}) error {
	ret := _m.ctrl.Call(_m, "Update", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Update", arg0, arg1)
}

// Mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockInterfaceRecorder
}

// Recorder for MockInterface (not exported)
type _MockInterfaceRecorder struct {
	mock *MockInterface
}

func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &_MockInterfaceRecorder{mock}
	return mock
}

func (_m *MockInterface) EXPECT() *_MockInterfaceRecorder {
	return _m.recorder
}

func (_m *MockInterface) GetToken(_param0 string) (*Token, error) {
	ret := _m.ctrl.Call(_m, "GetToken", _param0)
	ret0, _ := ret[0].(*Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockInterfaceRecorder) GetToken(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetToken", arg0)
}

func (_m *MockInterface) SendResetPasswordMail(_param0 string, _param1 *mailba.Mail, _param2 time.Duration) (*Token, error) {
	ret := _m.ctrl.Call(_m, "SendResetPasswordMail", _param0, _param1, _param2)
	ret0, _ := ret[0].(*Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockInterfaceRecorder) SendResetPasswordMail(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SendResetPasswordMail", arg0, arg1, arg2)
}

func (_m *MockInterface) UseToken(_param0 string) error {
	ret := _m.ctrl.Call(_m, "UseToken", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockInterfaceRecorder) UseToken(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UseToken", arg0)
}
